---
Parameters:
  ProjectName:
    Description: this is the project name
    Type: String
    Default: Udagram

Resources:
  #Load Balancer
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}ALB
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - Fn::ImportValue: !Sub ${ProjectName}-public-subnet-1
        - Fn::ImportValue: !Sub ${ProjectName}-public-subnet-2
      Tags:
        Key: Name
        Value: !Sub ${ProjectName}-ALB
      Type: application

Outputs:

...

# aws cloudformation validate-template --template-body=file://alb.yaml
# aws cloudformation create-stack --template-body=file://alb.yaml --stack-name=udagram-alb
# aws cloudformation update-stack --template-body=file://alb.yaml --stack-name=udagram-alb
